item {
    name: "1",
    id: 1,
    display_name: "rice leaf caterpillar"
}
item {
    name: "4",
    id: 14,
    display_name: "yellow rice borer"
}
item {
    name: "5",
    id: 15,
    display_name: "rice gall midge"
}
item {
    name: "10",
    id: 2,
    display_name: "rice water weevil"
}
item {
    name: "16",
    id: 6,
    display_name: "wireworms"
}
item {
    name: "23",
    id: 7,
    display_name: "armyworms"
}
item {
    name: "24",
    id: 8,
    display_name: "aphids"
}
item {
    name: "28",
    id: 9,
    display_name: "greenbug"
}
item {
    name: "29",
    id: 10,
    display_name: "bird cherry-oataphid"
}
item {
    name: "30",
    id: 11,
    display_name: "wheat blossom midge"
}
item {
    name: "33",
    id: 12,
    display_name: "wheat phloeothrips"
}
item {
    name: "34",
    id: 13,
    display_name: "wheat sawfly"
}
item {
    name: "14111",
    id: 3,
    display_name: "Rhopalosiphum maidis"
}
item {
    name: "14131",
    id: 4,
    display_name: "Dichocrocis punctiferalis"
}
item {
    name: "14141",
    id: 5,
    display_name: "Guenee Mythimnaseparata walker"
}
